### ISSUE TITLE
Zoom factor too strong by default for the browser preview?

### ISSUE THREAD

**Issue by xoofx** [madskristensen/MarkdownEditor#1]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.0.12

### Description
The zoom factor of the Markdown preview is too strong on my setup by default. Not sure why...

Currently I'm getting this:

![markdowneditor](https://cloud.githubusercontent.com/assets/715038/16177175/e2c5c950-3660-11e6-86ef-5f7ad88629e3.png)

While I would expect something more like this (I dezoomed with the ctlr+mouse wheel):

![markdowneditor2](https://cloud.githubusercontent.com/assets/715038/16177254/785adbf4-3661-11e6-95c6-03da5f518c68.png)

**Comment by madskristensen** [comment]
What's your OS DPI scaling if you have any?
