### ISSUE TITLE
Allow sync navigation to be disabled per document

### ISSUE THREAD

**Issue by xoofx** [madskristensen/MarkdownEditor#11]
Discussed in issue #2

We would like to have a button in the status bar to enable/disable live sync navigation per document (in addition to the global settings). This would not be persisted, just when editing.

**Comment by madskristensen** [comment]
So, I'm wondering about this one. You mentioned that it doesn't always work. However, I've yet to see it not working. What is the use case where you want this disabled?

**Comment by xoofx** [comment]
True that the current sync is quite accurate. Though, sometimes, I would like to edit one part of the doc and be able to watch another part. It's kind of using the preview as a split view...
So it is more a nice to have...

BTW, as part of the new FindClosestLine, I have removed the test `if (line < 3) line = 0` for navigation sync, as I don't see in which case this is annoying. If you have a repo doc, I could check this.

**Comment by madskristensen** [comment]
The `if (line < 3)` code is there to make sure that when you scroll to the top of the document, the preview always scrolls all the way up. Some markdown documents doesn't have anything that maps to what's at the top and therefore doesn't scroll up. I ran into it being annoying several times. I think we should leave it in

**Comment by xoofx** [comment]
Sure, but do you have a repo doc so that I can look at it?
