### ISSUE TITLE
Headings/Images not rendering in the Live Preview Window

### ISSUE THREAD

**Issue by JCPuerto** [madskristensen/MarkdownEditor#113]
### Installed product versions
- Visual Studio: Enterprise 2017 (26403.7)
- This extension: 1.11.201

### Description
The preview window is not working properly

### Steps to recreate
1. Install Visual Studio
2. Add this extension
3. Use the preview window

### Current behavior
The preview window works for links but not headings or images

### Expected behavior
It should preview everything including images and headings

![mdpreviewerror](https://cloud.githubusercontent.com/assets/10167695/25894964/f2f16c90-354b-11e7-8626-5d90cdffadcf.png)

**Comment by xoofx** [comment]
These are not a valid CommonMark:

- [ATX heading](http://spec.commonmark.org/0.27/#atx-headings) requires at least a space after `#`
- [URL Link destination](http://spec.commonmark.org/0.27/#link-destination) cannot have spaces (escape with `%20`)

**Comment by JCPuerto** [comment]
Thank you!
