### ISSUE TITLE
Smart tab not working from local vsix

### ISSUE THREAD

**Issue by xoofx** [madskristensen/MarkdownEditor#13]
Strange thing, the Smart tab features I added is not working when I install the local VSIX but is working properly if I run it in debug or release in the devenv Experience hive...

@madskristensen what could be wrong?

**Comment by madskristensen** [comment]
I see the same thing. Thought it was just my machine. It has to do with the html editor being the base of the markdown editor, but not in the exp instance. I'll investigate tomorrow

**Comment by xoofx** [comment]
If I disable Resharper (which is not in my experimental hive), it is working...

**Comment by madskristensen** [comment]
I've implemented a proper language service so that might fix it. Can you try with the latest?

**Comment by xoofx** [comment]
hm, not a big issue, but the tab is only working if I put the cursor at the beginning of the line, otherwise It does not work (while it works as intended in the Exp hive without Resharper installed...)

**Comment by xoofx** [comment]
What I don't understand is that none of the `CommandTargetBase` are called if the cursor is not at the beginning of the line, so ReSharper is catching this tab key at a higher level, but don't know where...

Hey @citizenmatt do you have any ideas where/how ReSharper is installing a hook for the tab key and how we could disable this? (we are in a custom language service, and I would not expect ReSharper to modify this...)

**Comment by madskristensen** [comment]
Closing since it is not actionable
