### ISSUE TITLE
Is it possible to insert line breaks (hard wrap) in links?

### ISSUE THREAD

**Issue by Ungerfall** [madskristensen/MarkdownEditor#141]
### Installed product versions
- Visual Studio: [example 2017 Professional]
- This extension: [example 1.1.214]

### Description
For some reason I tend to write readme files with 80 characters style. However, some web links might contain more. Therefore text like ``[msdn](https://docs.microsoft.com/en-us/iis/install/installing-publishing-technologies/installing-and-configuring-web-deploy-on-iis-80-or-later)`` needs to be wrapped.

### Things I've tried
1. Double space character and CR (according to [daring fireball](https://daringfireball.net/projects/markdown/syntax))
2. Tripple CR (according to [markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#line-breaks))
3. ``<br />`` tag

**Comment by xoofx** [comment]
It is currently not possible (CommonMark doesn't allow a space in an URL). See [babelmark](https://babelmark.github.io/?text=%5Bmsdn%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fiis%2Finstall%2Finstalling-publishing-technologies++%0A%2Finstalling-and-configuring-web-deploy-on-iis-80-or-later))... apart pandoc which is handling this, I don't see this being much supported.

You can bring this subject to http://talk.commonmark.org/
