### ISSUE TITLE
There is no preview..

### ISSUE THREAD

**Issue by cyciopes** [madskristensen/MarkdownEditor#144]
### Installed product versions
- Visual Studio: [2017 Community 15.4.4]
- This extension: [1.11.214]
- windows 7 enterprise x64
### Description
Preview are not working...

### Steps to recreate
1. install from Extensions and Updates
2. new item a markdown file
3. double click new md file
4. no preview 

Is it a bug? Or is it any setting to show the preview? 

![image](https://user-images.githubusercontent.com/21193224/33001972-2b506b48-cdec-11e7-8831-b4884badd897.png)

**Comment by cyciopes** [comment]
@BOT-Man-JL  Thanks reply.
I checked in "Extensions and Updates", it is enabled. And do you know anything why it was not running?

![image](https://user-images.githubusercontent.com/21193224/33109929-752e50ec-cf7f-11e7-9eb8-86397712017a.png)

**Comment by madskristensen** [comment]
Could it be some other extension such as ReSharper that takes over the .md files?

**Comment by cyciopes** [comment]
@BOT-Man-JL I've tired re-install several times, but no helping.
@madskristensen  I just install "VS 2017 Install Project" extension by myself, no others. They both can work well in my other PC.
Maybe i need re-install my VS?

**Comment by SauerKraut51** [comment]
No clue as to a solution, just noticing that in the solution explorer window the icon for your file is not as it appears for the md files in my VS2015 solution explorer window. 
![image](https://user-images.githubusercontent.com/27227303/34270432-2dc9871a-e656-11e7-8dac-7f18af51b665.png)

**Comment by cyciopes** [comment]
Thanks all. It works now after I update and repair my VS.
