### ISSUE TITLE
Markdown node in Options dialog is not sorted alphabetically

### ISSUE THREAD

**Issue by thirdwaffle** [madskristensen/MarkdownEditor#15]
### Installed product versions
- Visual Studio: 2015 Community
- This extension: 1.2.52

### Description
The Markdown node in the _Options_ dialog doesn't appear in alphabetical order like the other languages do. It appears at the bottom instead. Here's what I mean:

![image](https://cloud.githubusercontent.com/assets/10321525/16337091/24773ee4-3a56-11e6-8cc3-62fa54fc9187.png)

**Comment by madskristensen** [comment]
This has been fixed in the latest [CI build](http://vsixgallery.com/extension/9ca64947-e9ca-4543-bfb8-6cce9be19fd6/)
