### ISSUE TITLE
Pressing Tab and forced into code blockquote

### ISSUE THREAD

**Issue by markus-zhang** [madskristensen/MarkdownEditor#164]
### Installed product versions
- Visual Studio: [2017 Community]
- This extension: [example 1.12.233]

### Description
Pressing Tab and Markdown editor forces the style to code blockquote

### Steps to recreate
1. Input the following: 

VII. **Comments**

2. Press Enter
3. Press backspace to remove the auto generated characters (8)
4. Press Tab and enter whatever

### Current behavior
Whatever entered is considered as code

### Expected behavior
Should consider as text

![image](https://user-images.githubusercontent.com/3340464/44559469-47c5d000-a718-11e8-9095-ab51ce9191de.png)

**Comment by madskristensen** [comment]
This is not an issue, but now Markdown works
