### ISSUE TITLE
Typing after an inline code block causes jumping

### ISSUE THREAD

**Issue by drewnoakes** [madskristensen/MarkdownEditor#179]
### Installed product versions
- Visual Studio: 15.9.5
- This extension: 1.12.236

### Description

![](https://i.imgur.com/kZDdAla.gif)

### Steps to recreate
1. You may have to set a non-default editor font
2. Type an inline code block `` `code` `` followed by non-code and see how the text jumps left/right during typing.

### Current behavior
Code shouldn't jump around as it's distracting and headache inducing.

### Expected behavior
Code stays still on screen.

The inline code block is rendered using a different font in the edit area. I don't think this is necessary and removing that might fix the problem without requiring redesigning how on-screen text is formatted.

**Comment by drewnoakes** [comment]
I looked through "Fonts and Colors" and every single entry has the same font family and font size. Perhaps a font/size is hard coded in this extension directly?

**Comment by drewnoakes** [comment]
Inline code has a different font: 
![image](https://user-images.githubusercontent.com/350947/52056677-c4c46380-255a-11e9-87d8-421d5205e78d.png)

**Comment by drewnoakes** [comment]
Bingo:

 https://github.com/madskristensen/MarkdownEditor/blob/8028326ca710dd791cf629b382be776719b8caca/src/Classifier/MarkdownClassificationTypes.cs#L86-L90

I'll submit a PR that removes this hard coded font.

**Comment by madskristensen** [comment]
This is fixed in the new preview extension https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor2

**Comment by drewnoakes** [comment]
Verified the fix, thanks!
