### ISSUE TITLE
Add support for TOC navigation

### ISSUE THREAD

**Issue by xoofx** [madskristensen/MarkdownEditor#18]
It is often very convenient to navigate easily to a heading in a document. The extension should provide a way to easily access the TOC and navigate to it.

Would be also perfect if it was keyboard friendly.

**Comment by xoofx** [comment]
started to work on this.

**Comment by xoofx** [comment]
So @madskristensen, I have pushed a preview of the TOC navigation:

- I put the combo into the bottom margin at the right of the Zoom, don't know if it is enough fine here. I didn't want to clutter the top margin just to add this.
- The combo updates on caret position changes
- I don't know how to change the background color of the combo box (some XAML/VS styling voodoo is needed here) to make it match the other combo box (well, there is a VS styling for combo box that I'm missing obviously)
- I haven't added a keyboard-key (I was thinking about CTRL+SHIFT+G) to allow to open the drop down box and navigate inside it (It will require and explicit Focus() on the editor side on the carte position of the selected heading)
- there are maybe some async/concurrency problem that I will have to handle a bit more carefully

Let me know what you think, feel free to modify it!

**Comment by madskristensen** [comment]
Why not use the IGraphProvider (progression API) to create the outline in Solution Explorer in virtual nodes nested under the .md file? Then no sync is needed

**Comment by madskristensen** [comment]
...Or use the Document Outline window. It's under View -> Document Outline

**Comment by madskristensen** [comment]
When using source control, having the dropdown next to the scrollbar is taking up a lot of real-estate

![image](https://cloud.githubusercontent.com/assets/1258877/16394780/ca29ffb8-3c6b-11e6-91bd-15f92130630a.png)

**Comment by xoofx** [comment]
Yeah, I realized that. 

I don't like much the other options:
-  Document outline is barely used, takes lots of spaces, you need to open and dock it.
- The solution explorer is not great either. Some Markdown documents I'm using have several dozens of headings, quite nested + it doesn't fit well with live update.

So maybe moving this to the top margin, as it is done for methods navigation then? Though, if you have an idea how to get the same styling than for the other combobox that would be great!

**Comment by madskristensen** [comment]
I think there might be an API we can use that adds the top dropdowns like in C#. Let me check.

**Comment by madskristensen** [comment]
I just committed a class called DropDownBars.cs. There's a TODO comment showing where to add the document outline

**Comment by madskristensen** [comment]
I've made the example inside DropDownBars.cs easier to use. It uses the old VS APIs though, so there is no ITextSnapshot etc.

**Comment by xoofx** [comment]
amazing, will update with this

**Comment by madskristensen** [comment]
Actually, it looks like you need to override `OnItemChosen` and/or `OnitemSelected` and then handle navigation yourself

**Comment by xoofx** [comment]
@madskristensen I have updated the code. Looks to work quite well and it is more nicely integrated with this drop down box. Though at some point I had an issue with the browser crashing... not sure if I did something wrong in the code (concurrency/thread safe issues?). Let me know!

**Comment by xoofx** [comment]
@madskristensen question: Is there a way to plug a keyboard shortcut (CTRL+SHIFT+G) bound to open the dropdown box?

**Comment by madskristensen** [comment]
Let's see if there already is a keybinding for showing the dropdown. I'll take a look. If not we can do it manually

**Comment by madskristensen** [comment]
Ctrl+F2 puts focus on the navigation bar

**Comment by madskristensen** [comment]
We can use _Shift+Alt+Up_ and _Shift+Alt+Down_ to navigate the caret in the document between headings.

**Comment by madskristensen** [comment]
We can use Ctrl+PageUp and Ctrl+PageDown to navigate between headings in the document without touching the navigation bar at all

**Comment by xoofx** [comment]
Awesome, super convenient these shortcuts!

FYI, I  have swapped the combo and display the headings now in the left combo (so it is directly accessible by a CTRL+F2)

**Comment by madskristensen** [comment]
I get an internal reflection error now and the preview window doesn't show up. Did you commit everything?

**Comment by xoofx** [comment]
as I mentioned earlier, I was getting sometimes some crashes in the Browser, but haven't found yet when it occurs exactly

**Comment by xoofx** [comment]
Just pushed at least this commit 77c54bd8c3c885c8b86a620c13d0b4b78e75bb09 but I don't think that's the problem

**Comment by madskristensen** [comment]
I fixed the issue. It had to do with async dispatching it seems like
