### ISSUE TITLE
Sync Scrolling with Images

### ISSUE THREAD

**Issue by spottedmahn** [madskristensen/MarkdownEditor#183]
### Installed product versions
- Visual Studio: 2019
- This extension: 1.12.236

### Description
The sync scrolling feature doesn't seem to work for me.  I imagine the problems is related to images.

### Steps to recreate
1. Start a markdown file
2. Put some text in and a few images such that the vertical scrollbar is enabled
3. Try to edit something at the bottom of the md file (the preview doesn't scroll down there)

### Current behavior
It's not scrolling to the place I'm editing.

### Expected behavior
Scroll to the place I'm editing.

**Comment by alaendle** [comment]
Reproducible (at least for me) with:
Microsoft Visual Studio Professional 2019 Preview - Version 16.6.0 Preview 3.0
Markdown Editor   **1.12.253**

**Comment by SetTrend** [comment]
Same here:

![Markdown Editor - Text Editor and Designer are not in sync](https://user-images.githubusercontent.com/9283914/97908824-83707180-1d47-11eb-9af4-fc82336580e6.png)

Bubbling up ...

**Comment by grumat** [comment]
reproducible. Happens to with a long Bullet list.

**Comment by spottedmahn** [comment]
wonder if the new extension will address this? 🤔

https://github.com/MadsKristensen/MarkdownEditor2022

**Comment by madskristensen** [comment]
No, but I should fix it in the new extension

**Comment by madskristensen** [comment]
I just fixed it in the new extension. A new version is being uploaded in a few minutes ready to be tested out
