### ISSUE TITLE
Other extensions not working in Markdown Editors Windows

### ISSUE THREAD

**Issue by Molinarius** [madskristensen/MarkdownEditor#19]
### Installed product versions
- Visual Studio: 2015 Professional Update 2 (Windows 7)
- This extension: 1.3.81

### Description
I noticed that some other extensions are not working in Markdown editor windows, e.g. Trailing Whitespace (I checked the Ignore Pattern setting), Visual Studio Spell Checker, Visual Assist X (e.g. Highlight matching words). With Markdown Editor disabled, or with plain text files, they work, so I assume it has to do with Markdown Editor.

I don’t know for sure if that’s a bug or a feature, but I wanted to let you know.

### Steps to recreate
1. Install Markdown Editor and Trailing Whitespace Visualizer
2. Remove .md from Options / Environment / Trailing Whitespace / Ignore pattern
3. Open or create a .md file and add trailing whitespace
4. Optional: Install Visual Studio Spell Checker and / or other extensions and check with them.

### Current behavior
Trailing whitespace is not visualized.

### Expected behavior
Trailing whitespace should be visualized.

**Comment by madskristensen** [comment]
Fixed in latest [CI build](http://vsixgallery.com/extension/9ca64947-e9ca-4543-bfb8-6cce9be19fd6/)
