### ISSUE TITLE
Image name doesn't support Chinese.

### ISSUE THREAD

**Issue by wakuflair** [madskristensen/MarkdownEditor#20]
### Installed product versions
- Visual Studio 2015
- This extension: 1.3.81

### Description
I pasted an image and saved it with a Chinese file name, and the preview can't show it.
(BTW: The Web Essential extension did support chinese file name.)

**Comment by madskristensen** [comment]
@xoofx Markdig appears to encoding the file name.

`![你好](你好.png)` becomes `<img src="%E4%BD%A0%E5%A5%BD%E5%90%97.png" alt="你好吗" />`

**Comment by xoofx** [comment]
Hm, haven't checked implementation but afaik URLs have to be encoded and cannot contain non ASCII characters no?

**Comment by madskristensen** [comment]
Not sure, but the encoded URI doesn't work so something is up

**Comment by madskristensen** [comment]
Something like this may be all that's needed:

`Uri.EscapeUriString(url)`

**Comment by xoofx** [comment]
@madskristensen strange for me it becomes: `<img src="%E4%BD%A0%E5%A5%BD.png" alt="你好" />`

**Comment by madskristensen** [comment]
Maybe depends on the source file encoding

**Comment by wakuflair** [comment]
@madskristensen I saved my markdown file using both UTF-8 and ASCII encoding, and neither of therm can show the image. So I don't think it's depends on the source file encoding

**Comment by wakuflair** [comment]
@xoofx  IMO, the file name shouldn't be encoded. After all, other markdown editors leave the file name as plain text.(old Web Essential, Visual Studio Code...)

**Comment by xoofx** [comment]
This is fixed by commit  2b54955
