### ISSUE TITLE
Text jitters when typing after inline code

### ISSUE THREAD

**Issue by DillonAd** [madskristensen/MarkdownEditor#205]
### Installed product versions
- Visual Studio: 2019 Professional v16.6.1
- This extension: 1.12.253

### Description

When typing into the editor, the text jitters. This happens with the Word Wrap option enabled and disabled. 

### Steps to recreate
1. Create Markdown file
2. Add a H2 Markdown element (##) with a block of text underneath
3. Add an inline code fence (\`code here\`) to the block of text
4. Add text to the end of the block of text

GIF of the issue in action:
![MarkdownEditorGlitch](https://user-images.githubusercontent.com/28228453/85305980-74151980-b473-11ea-8cbf-e38a6b62df3d.gif)

File used to reproduce the issue (I had to add the ".txt" extension to allow the upload):
[README.Test..md.txt](https://github.com/madskristensen/MarkdownEditor/files/4814125/README.Test.md.txt)

### Current behavior
Text jitters while the user is typing in Step 4.

### Expected behavior
The text will not jitter while being edited.

Thanks!

**Comment by StingyJack** [comment]
That has been happening in different ways for a while  https://github.com/madskristensen/MarkdownEditor/issues/175

**Comment by madskristensen** [comment]
This is fixed in the new preview extension https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor2

**Comment by DillonAd** [comment]
Finally got to test this with the latest version and the experience is smooth and amazing! Thank you!
