### ISSUE TITLE
Feature request: fold by headings

### ISSUE THREAD

**Issue by deerchao** [madskristensen/MarkdownEditor#21]
It would be nice to be able to fold by headings(h1, h2, h3, etc.), just like Navigation Panel in Microsoft Word, this way we can edit long documents much easier.

Say, we have a document:
# h1
## h2
paragraph 1

    code
### h3
paragraph 2
## h2
paragraph 3

we should be able to fold at h1 all content between this h1 and the next h1/eof;
we should be able to fold at h2 all content between this h2 and the next h2/h1/eof;
we should be able to fold at h3 all content between this h3 and the next h3/h2/h1/eof;

**Comment by madskristensen** [comment]
Thanks for the suggestion!

Install the [CI build](http://vsixgallery.com/extension/9ca64947-e9ca-4543-bfb8-6cce9be19fd6/) to verify that the feature works as expected

**Comment by madskristensen** [comment]
Perfect repo. Thanks. This has now been fixed

**Comment by deerchao** [comment]
Cool! Now it works perfectly, Thanks!

**Comment by weitzhandler** [comment]
I'm using this extension in VS 2022. I can't see the collapsible heading controls:

![image](https://github.com/madskristensen/MarkdownEditor/assets/2716316/a941b428-59a1-4042-bdb5-386a5b1a98d3)
