### ISSUE TITLE
Disable auto-complete

### ISSUE THREAD

**Issue by Bitfiddler** [madskristensen/MarkdownEditor#215]
### Installed product versions
- Visual Studio: Microsoft Visual Studio Professional 2019 Version 16.9.1
- This extension: 1.12.253

### Description
Would it be possible to have an option so that the editor does not try to auto-complete text as you write it?
It's disruptive to be typing 'the' and hit space only to have it be replaced with "EntityTagHeaderValue". 

### Steps to recreate
1. Create a new .md file in an existing large project
2. Start typing
3. Witness all sorts of interesting replacements.

### Current behavior
It's replacing text elements with code elements (variable, function and class names) as I type.

### Expected behavior
Have this behavior be optional.  Perhaps a key binding to enable/disable it.  I mean it's great if you are writing some code in your MarkDown to have auto-complete fill in actual code element names, but if you are writing plain English documentation, it is maddening.

**Comment by madskristensen** [comment]
The extension doesn't provide any auto complete. It only happens with the default textmate based support in VS, so that's probably what you're seeing
