### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by scottkuhl** [madskristensen/MarkdownEditor#218]
### Installed product versions
- Visual Studio: 2022 All Versions

### Description
Make the extension available in Visual Studio 2022.

### Steps to recreate
1. Download the extension installer.
2. Run the installer.

### Current behavior
Message that it is already installed to all applicable products appears even though it is not installed in Visual Studio 2022.
It is also not listed in Online Extensions in Manage Extensions Visual Studio 2022.

### Expected behavior
Installs and works in Visual Studio 2022.

_Note: Sorry for the all the extra details.  I probably could have stopped with the title on this one._

**Comment by RudolfJan** [comment]
I would love to see an updated version for at least Visual Studio 2019. and for newer versions as well. It is a nice tool and especially the integration in Visual Studio is appreciated.

**Comment by tzographos** [comment]
I second that... One of the most useful extensions

**Comment by digitaldias** [comment]
Bump! We need danish stuff in VS!

**Comment by lsoft** [comment]
hey guys. I has converted this vsix for vs2022; the initial version is here: https://github.com/lsoft/MarkdownEditor/tree/branches/vs2022_support

please compile it, run it and give me feedback; I've finished doing it only today, so bugs are expected.

if that vsix2022 will work fine, I'm planning to create a PR here.

**Comment by madskristensen** [comment]
I will convert it for vs2022, but I'm on paternity leave at the moment

**Comment by RudolfJan** [comment]
Great, Mad, we can wait a while still

**Comment by lsoft** [comment]
may be this PR will help Mads to save few hours https://github.com/madskristensen/MarkdownEditor/pull/220

**Comment by madskristensen** [comment]
Grab it here: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor64

**Comment by michaelcheers** [comment]
Or the latest version: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor2
