### ISSUE TITLE
live preview does not maintain cursor position 

### ISSUE THREAD

**Issue by groogiam** [madskristensen/MarkdownEditor#221]
### Installed product versions
- Visual Studio: Visual Studio 2019 Community and Enterprise (probably all editions)
- This extension: 1.12.253

### Description
The live preview does not maintain the cursor position. Every time a new character is typed the preview scrolls back to the top. This makes it very hard to use the live preview as you continually have to scroll down the page to see your changes.

### Steps to recreate
1. Open a long mark down document
2. Scroll to the bottom of the document
3. Make some edits.

### Current behavior
Preview refreshes but it is focused at the top of the page. 

### Expected behavior
Preview should be refreshed and scrolled to the current edition position.

**Comment by bradykelly** [comment]
Also on Visual Studio 2022 Enterprise extension version 1.13.263

**Comment by madskristensen** [comment]
This should now be fixed in the new extension https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor2

**Comment by groogiam** [comment]
Just installed the new version and its working great. Thanks.
