### ISSUE TITLE
Please support more location settings

### ISSUE THREAD

**Issue by a44281071** [madskristensen/MarkdownEditor#23]
Can you support left/top/right/bottom to locate preview window?
I used to coding in middle screen.
But now I'm always twist the neck to see the left.
Thanks.

**Comment by madskristensen** [comment]
@a44281071, bottom is supported now. Does that meet your needs?

**Comment by a44281071** [comment]
@madskristensen I'd like editor at right, and previewer at Middle, last, Solution Layer(Folder Listing) at right.

**Comment by madskristensen** [comment]
No votes given to this item by other users. Closing
