### ISSUE TITLE
Spell check and auto correct

### ISSUE THREAD

**Issue by tdykstra** [madskristensen/MarkdownEditor#24]
Would it be possible to get spell check and auto correct?

**Comment by madskristensen** [comment]
There is already spell checking extensions and they should work correctly with this editor. There's this one https://visualstudiogallery.msdn.microsoft.com/a23de100-31a1-405c-b4b7-d6be40c3dfff and this one https://visualstudiogallery.msdn.microsoft.com/7c8341f1-ebac-40c8-92c2-476db8d523ce

I haven't tried them myself though

**Comment by tdykstra** [comment]
Thanks, I'll check those out.

**Comment by tdykstra** [comment]
@madskristensen Spell checker doesn't seem to work with markdown files in Markdown Editor.

**Comment by tonemackay** [comment]
@madskristensen I am using the Visual Studio Spell Checker extension and it has stopped working on markdown files since installing the Markdown Extension.

**Comment by axelheer** [comment]
See EWSoftware/VSSpellChecker#93

**Comment by EWSoftware** [comment]
@axelheer, @tonemackay: I've added a pull request to add a classification I need to properly support spell checking for markdown files with this extension.  Once merged, I can add the tagger needed to support spell checking to the next release of my spell checker extension.
