### ISSUE TITLE
Custom CSS for preview

### ISSUE THREAD

**Issue by mcnameej** [madskristensen/MarkdownEditor#26]
### Enhancement request

There should be a way to specify a custom CSS file for the preview.  Ideally there would be a way to set a global default in the VS options, and a way to override that on per-project and per-file basis.

My use case is that the MD files I'm editing will ultimately become pages in a static web site. The formatting of some key elements (code blocks, definition lists, unordered lists, and tables) is quite different with my CSS compared to the default. I don't need the preview window to **exactly** match the final output, but I'd really like to get it closer.

**Comment by akzaidi** [comment]
Would love this feature. VS Code does a good job of matching the preview pane to the VS theme: [VS Code Markdown](https://code.visualstudio.com/Docs/languages/markdown)

**Comment by corydeppen** [comment]
Hoping since Web Essentials allowed for a custom style sheet it's just a matter of time before we see something similar in Markdown Editor.
