### ISSUE TITLE
Allow links in preview mode to open in default web browser

### ISSUE THREAD

**Issue by RyanWittibschlager** [madskristensen/MarkdownEditor#27]
Is this possible? Our code won't be published to github, and it would be nice to use the preview mode as our de facto markdown reader within VS 2015. Having clickable links would be great (without having to ctrl-click the link in the markdown editor)

**Comment by madskristensen** [comment]
Non-local links should already open in default browser when clicked on in the preview window. Can you please provide a repro of a link that isn't clickable?

**Comment by madskristensen** [comment]
This is fixed in the latest version
