### ISSUE TITLE
Current line is deleted when pressing return at the start of it

### ISSUE THREAD

**Issue by xt0rted** [madskristensen/MarkdownEditor#29]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.5.110

### Description
The editor is deleting lines when pressing return at the start of the line.

### Steps to recreate
Add the following text to a document
```markdown
### Some Heading
- A list item
```
Then put your cursor at the start of the second line and press return.

### Current behavior
The line you're on is deleted

### Expected behavior
The line shouldn't be deleted and a new line should be added

**Comment by madskristensen** [comment]
@xoofx wanna take a look?

**Comment by xoofx** [comment]
@madskristensen sure, I will. I'm still on holidays for few weeks with sporadic Wifi access, but should be able to take a look in the coming days 😅

**Comment by madskristensen** [comment]
@xoofx Thanks. Enjoy your vacation. No rush on this

**Comment by dls314** [comment]
If it helps in diagnosis, I only see this behavior when editing lists.

**Comment by robbie-mac** [comment]
@madskristensen @dls314 Also on blockquotes

**Comment by madskristensen** [comment]
@xoofx Any update on this? Do you want me to take a look?

**Comment by xoofx** [comment]
@madskristensen not until next week (home installation, still no desktop computer)

**Comment by xoofx** [comment]
FYI just started to work on it, a bit more problematic than expected, fixing stuff has side effects making things worse... will try to find a better smart completion than the buggy current one...

**Comment by madskristensen** [comment]
Awesome. Thanks 👍

**Comment by xoofx** [comment]
The commit 82d9618 should fix this issue, hopefully with a better smart indent experience.
