### ISSUE TITLE
Urls are being injected with emojis

### ISSUE THREAD

**Issue by xt0rted** [madskristensen/MarkdownEditor#3]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.1.25

### Description
Urls are being injected with emojis.

### Steps to recreate
1. Add a plain url to the document such as `http://bing.com`

### Current behavior
The url is converted to `http😕/bing.com`

### Expected behavior
`:/` shouldn't be converted to an emoji

**Comment by madskristensen** [comment]
Thanks for the bug. That's a high priority one

Opened it on Markdig repo https://github.com/lunet-io/markdig/issues/15. Closing this one
