### ISSUE TITLE
More hotkeys

### ISSUE THREAD

**Issue by tdykstra** [madskristensen/MarkdownEditor#34]
### Description
Can we get hotkeys for the "suggested actions shown in light bulbs"?  Especially useful for link and image, but also for block quote and code block (ctrl-C is for in-line).

**Comment by madskristensen** [comment]
Can't you use `Ctrl+.` to invoke the light bulbs and then use arrow keys to select the right one?

**Comment by tdykstra** [comment]
Good point.  It's an extra keystroke or two, not much of an issue for things used relatively infrequently, and links which I do use frequently are the default entry.
