### ISSUE TITLE
Curly braces in code blocks break down stream rendering

### ISSUE THREAD

**Issue by xt0rted** [madskristensen/MarkdownEditor#4]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.1.25

### Description
I have a code block like so in on of my documents `http://{domain}/callbacks` and after this renders none of the down stream headers do, but their content does.

### Steps to recreate
1. Use markdown from https://gist.github.com/xt0rted/a1b5d6383ada881ec9fb72e576758931

### Current behavior
Headers after the code block aren't rendered.

![markdowneditor](https://cloud.githubusercontent.com/assets/831974/16182393/8a4cf880-3673-11e6-8b55-6a72979ca837.png)

### Expected behavior
Headers should be rendered.

**Comment by madskristensen** [comment]
This is being tracked at https://github.com/lunet-io/markdig/issues/16

Closing here

**Comment by madskristensen** [comment]
Thanks for the bug reports. Both the Markdown Editor and Markdig are relatively new projects so please keep them coming. 👍
