### ISSUE TITLE
Support tables using pipe syntax

### ISSUE THREAD

**Issue by uselesshasid** [madskristensen/MarkdownEditor#42]
Visual studio Team Services does not support html tags inside markdown files. But they do support [githubs' pipe syntax for tables](https://help.github.com/articles/organizing-information-with-tables/). So if i want to create markdown files with tables that are supported on both platforms, pipe syntax is the only way to go.

**Comment by madskristensen** [comment]
This extension does support GitHub's table syntax. All the examples in the link you provided renders correctly. Are you seeing pipe tables not working in this extension? If so, can you provide a snippet that fails to render as a table?

**Comment by uselesshasid** [comment]
You are right, sorry. I tried micrsoft's example for some reason when i copied over it didn't work, but now when i tried again it does work. Thanks!
