### ISSUE TITLE
CTRL+B shortcut doesn't works

### ISSUE THREAD

**Issue by midiway** [madskristensen/MarkdownEditor#45]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.7.148]

### Description
CTRL+B shortcut is not working, it does nothing with my selection, though CTRL+I does work. 
I think there is some CTRL+B shortcut handler with higher priority then this extension.
In Options / Keyboard, selecting HTML editor, and then CTRL+B, reveals a list of 'Shortcut currently used by' where the first item is `Debug.FunctionBreakpoint`.

**Comment by madskristensen** [comment]
Do you have ReSharper installed by chance? If so and you disable it, does the issue go away?

**Comment by midiway** [comment]
No ReSharper installed
