### ISSUE TITLE
Pulling the preview splitter left extends the preview over solution explorer

### ISSUE THREAD

**Issue by jesperll** [madskristensen/MarkdownEditor#5]
### Installed product versions
- Visual Studio: 2015 Enterprise 14.0.25123.00 Update 2
- This extension: 1.1.33
### Description

Pulling the preview splitter left extends the preview over solution explorer - i.e. outside the document window region

![image](https://cloud.githubusercontent.com/assets/33271/16193066/3c763b42-36ed-11e6-9326-491ec237d369.png)
### Steps to recreate
1. Open a .md file
2. Grab the splitter between raw and preview and drag left (if i'm careful I can get it to overlap partially - otherwise it extends to the edge of VS windows)
### Current behavior

It overlaps my solution explorer
### Expected behavior

It should stay within its document window region

**Comment by madskristensen** [comment]
Wow, that's pretty crazy looking :)

**Comment by madskristensen** [comment]
Fixed by #89
