### ISSUE TITLE
Editor font preview is Courier New instead of Consolas

### ISSUE THREAD

**Issue by ygoe** [madskristensen/MarkdownEditor#52]
### Installed product versions
- Visual Studio 2015 Community
- This extension 1.7.150

### Description
The Markdown source editor shows regular text in the Consolas font, but indented code text in the Courier New font. This cannot be changed in the settings.

### Steps to recreate
1. Type 4 spaces followed by text

### Current behavior
Courier New

### Expected behavior
Consolas, like every other code text in Visual Studio

**Comment by ygoe** [comment]
The same applies to `code formatted with backticks`.

**Comment by madskristensen** [comment]
The VS options dialog doesn't support changing the type face for individual classifications, unfortunately.

**Comment by ygoe** [comment]
And where do these classifications come from? Somebody must have written the code that picks "Courier New" when the rest of the document is "Consolas".

**Comment by madskristensen** [comment]
It's written in this extension. If it was consolas, then there would be no visible difference between code blocks and the rest of the code. Only color, bold and italic would be available to modify which isn't enough to give the sense that it is a block of code IMO. What's the issue with Courier New?

**Comment by ygoe** [comment]
I don't like that font very much, that's all. But it's not so much of a difference to Consolas that it would be easily distinguishable from the other formatting. I'm somewhat surprised anyway that there is a "poor man's" preview in the source panel with the real preview in the other panel. Could I maybe choose to disable some or all of the previews in the source view? I haven't seen an option for that.

**Comment by madskristensen** [comment]
@ygoe I guess that would make sense. Are you thinking of a setting that would completely disable all classifications in the source view such as bolding headers, making links blue etc?

**Comment by ygoe** [comment]
As an extreme form, yes. I haven't used this extension for a long time yet so I can't say how it would feel without these extras. Maybe several separate options would be useful so that everybody can pick the formats they want.

I noticed the option to disable the preview panel. Does that mean that only the source editor remains? In that case it would probably make more sense to show some basic formats in the source itself. In that case, the closest format would be setting the background to grey (instead of changing the font to just another monospace).

**Comment by seangenabe** [comment]
The Courier New thing for me is a deal-breaker. Courier New sucks. There should be a way to either change the code block font family, or turn this off completely and just inherit from the global text font family. Not everyone wants distinct code block font families from the rest of the code. That looks like a fancy rich text editor, which is a long stretch at what Markdown aims to _be_, which is to be readable even without rendering. Just look at Github. Maybe just change the text foreground/background color?

**Comment by c-lipka** [comment]
> It's written in this extension. If it was consolas, then there would be no visible difference between code blocks and the rest of the code. Only color, bold and italic would be available to modify which isn't enough to give the sense that it is a block of code IMO. What's the issue with Courier New?

Chiming in here because I've just tested your plug-in, and the Courier New font bothers me as well: When editing MD files, I want to see the file in a fixed-width font. Courier New's differing pitch screws this all up.

Since in _my_ opinion background/foreground color, bold and italic _are_ sufficient to mark code as such, I second the motion for an option to disable the "Markdown Code" font override.

**Comment by kkm000** [comment]
Yes, pretty please! The major problem for me is the line length. I am trying to write neat markdown files, readable without rendering, so am wrapping them at a consistent right margin. The varying font makes lines that contain backticks look much longer that they really are. I have to glance at the column counter in the status bar all the time--and then wonder whether I actually must trade the convenience of editing in fixed font to the convenience of previewing the rendered look.

May I have both please? An option to turn off all bells and whistles except the rendering preview pane would do just fine!
