### ISSUE TITLE
First code line after list item has wrong font for opening spaces

### ISSUE THREAD

**Issue by breyed** [madskristensen/MarkdownEditor#53]
With this markdown:

    1. Some list item

            some code
            more code

The lines "some code" and "more code" are not aligned in the editor, although they are fine in the preview window. If you turn on View White Space, you can see that the first three spaces on the line "some code" are in the default font, rather than the code font.

Once you understand what is happening, it's just cosmetics, but until you do, it feels like tabs and spaces are being swapped out or other craziness is happening. This especially happens if you try to align the two lines or insert a paragraph between the list item and the code, which causes the code block to appear to have a mind of its own.

The same thing happens when using back ticks to markup text in-line.

Versions:
- Visual Studio 2015 Enterprise Update 3
- Markdown Editor 1.7.150

**Comment by xoofx** [comment]
Could you post a screenshot of the problem?, We had this problem in the past in the issue #8 and I thought that it was fixed, suspected first ReSharper...but now I'm no longer sure it was fixed (but can't still reproduce it...)

**Comment by xt0rted** [comment]
I just installed the most current CI build and this is still happening with inline code blocks, not sure if that's related to this or not. All of my markdown & ReSharper settings are set to use Consolas. Suspending ReSharper doesn't change the text style.

**Comment by xoofx** [comment]
@xt0rted the issue above is not related to inline but tab code blocks on the 2nd line of a code block. Are you experiencing the same issue?

**Comment by xt0rted** [comment]
Yea I can repro this. The other issue I'm seeing is the code formatting gets applied when there's 7 spaces so if you're using multi line editing to add spaces to both lines at once then when you hit 7 spaces on the first line the formatting is applied and the second line auto inserts an 8th space. It's also allowing the cursor to be placed on the empty line farther to the right than it should be.


<img width="404" alt="markdown" src="https://cloud.githubusercontent.com/assets/831974/18752810/93df1b84-80b1-11e6-9ced-a05dc5126f94.png">
<img width="423" alt="markdown2" src="https://cloud.githubusercontent.com/assets/831974/18752809/93db887a-80b1-11e6-9fee-4374bfe682ca.png">
<img width="396" alt="markdown3" src="https://cloud.githubusercontent.com/assets/831974/18752811/93dfc778-80b1-11e6-97b6-6cb122f04f22.png">

**Comment by madskristensen** [comment]
I can repro. It looks odd but I didn't see it at first

**Comment by xoofx** [comment]
The problem is in markdig that is incorrectly starting the span on the 3 characters. I will have a look.

**Comment by xoofx** [comment]
The commit 2270d2d should hopefully fix this issue
