### ISSUE TITLE
word wrap doesn't work with Rmd

### ISSUE THREAD

**Issue by akzaidi** [madskristensen/MarkdownEditor#58]
### Installed product versions
- Visual Studio: VS 2015 Community/Professional
- Markdown Editor 1.7.154

### Issue

I've been using your extension with [rmarkdown files](http://rmarkdown.rstudio.com/). The preview works automatically, and overall looks great. Unfortunately, word wrap doesn't work:
![image](https://cloud.githubusercontent.com/assets/1307603/18437037/a76b6208-78ea-11e6-95c4-1a8219f6c41d.png)

There's no value in Options -> Editors for Rmarkdown. Without the extension, Rmarkdown are automatically word-wrapped (using the [RTVS extension](github.com/Microsoft/RTVS))

### Steps to recreate
1. Open a Rmd file with long text chunks

**Comment by madskristensen** [comment]
Word wrap works fine for me for markdown (.md) files. You enable it here:

![image](https://cloud.githubusercontent.com/assets/1258877/18590975/9aa8ad02-7be5-11e6-8d7b-e270c6427b81.png)

I'm not too familiar with _R Markdown_ and I know that this extension doesn't open .rmd files automatically in the Markdown editor provided by this extension

**Comment by madskristensen** [comment]
Actually, that's an issue in the R tooling extension for VS and not this extension. Please file a bug on the R tooling repo
