### ISSUE TITLE
Implementing line auto completion on enter in tasks/list/blockquote

### ISSUE THREAD

**Issue by xoofx** [madskristensen/MarkdownEditor#6]
This is a question. I would like to implement auto completion when pressing the return key inside a tasks/list/blockquote/code indent...etc. It would basically go to next line and add the proper list/blockquote/tasks (supporting nested) automatically, with the correct indentation (and double return would break the pending blockquote/list). It is a bit like an auto-indent, but it is not only indentation but also characters used by the structure ( `>` or `-`...etc.)

But I'm a bit lost with the correct way to do it: Should it go through a `IKeyProcessorProvider`?  or a `ICompletionSource`? Or through `IIntellisenseController`? a `IOleCommandTarget`? a `IVsExpansionClient`? another method?

**Comment by madskristensen** [comment]
Let me ask the devs what is the best approach. It's a good idea

**Comment by madskristensen** [comment]
First of, we need SmartIndent support. I'll add that now. Then we can add to it to support list item scaffolding etc.
