### ISSUE TITLE
Lots of extensions are disabled when I enable Markdown Editor

### ISSUE THREAD

**Issue by ncarandini** [madskristensen/MarkdownEditor#62]
### Installed product versions
- Visual Studio: 2015 Ultimate
- This extension: 1.8.159

### Note
This issue is related to Markdown Editor and also to all the other extensions listed below.

### Description
The extensions listed below are all disabled when I enable one of those  extension (all made by you but one):
- Add New File
- Browser Reload On Save
- Browser Sync
- _Cloud Explorer for Visual Studio 2015 (by Microsoft)_
- Editor Enhancements
- File Nesting
- Image Optimizer
- Image Sprites
- JavaScript Snippet pack
- Markdown Editor
- Open Command Line
- Package Installer
- Suggested Extensions
- Web Accessibility Checker

### Steps to recreate
1. Open the "Extensions and Updates" window
2. Enable one of the previous listed extensions
3. Restart VS
4. Open the "Extensions and Updates" window again
5. Verify that all the listed exceptions are disabled but the one enabled on step 2

### Current behavior
Enabling an extension from the listed ones disable all the others.

### Expected behavior
Each extension should be enabled or disabled without affecting the other ones.

**Comment by ncarandini** [comment]
Partially solved with these steps:
 1. Delete the Visual Studio component cache is located at `%localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache`
 2. Open VS and the "Extensions and Updates" window
 3. Enable all the disabled extensions
4. Restart VS

Still some extensions are disabled, but now the list is much smaller:
- Add New File
- Browser Reload On Save
- Browser Sync

**Comment by ncarandini** [comment]
Gotcha!
I've found the workaround, and maybe this can be a hint to find the bug in VS Extension and Updates functionality and/or these extensions, while still I don't understand why only some extensions have this strange behaviour.

1. Don't bother to delete the Visual Studio component cache
2. Open VS and the "Extensions and Updates" window
3. Enable a disabled extension that turns up the "Restart VS" message
4. Now "touch" every extension in the above big list. By touch I mean:
  - enable it if disabled
  - disable it and the re-eable it again if already enabled (this is the workaround!)
5. Restart VS and now you shoud find everything enabled.

I know this is not reproducible on all VS istances, but solved the issue for me.
More over maybe this can help VS team to check the Extension and Updates code...

**Comment by madskristensen** [comment]
Thanks for posting the workaround. This has been a pain point for a long time for a lot of extension users.

/cc @timsneath @alexeyler

**Comment by ncarandini** [comment]
Thanks Mads,
but I've discovered right now that this workaround solve the "enable one --> disable all others" dilemma, but it is only temporary, till another extension is installed / updated.
After that, all the extensions of the above big list is disabled again :-(

**Comment by mcnameej** [comment]
You may want to try [DuplicateExtensionFinder](https://github.com/remcoros/DuplicateExtensionFinder). It fixed the problem for me when I was having enable/disable weirdness.

**Comment by ncarandini** [comment]
Problem solved, you made my day :-)
 In fact the duplicated extensions were exactly those of my big list.
Thank you so much.
