### ISSUE TITLE
Prevent extension from crashing and exception report

### ISSUE THREAD

**Issue by xoofx** [madskristensen/MarkdownEditor#63]
Currently, if there is a bug in Markdig (or collateral elsewhere in the MarkdownEditor code), the exception may crash the extension (and most likely crash VS?). There are some reports about this (see issue related #61 and others I received privately), but they usually don't provide enough information so we can't really help here. 

It would be great if we could add some safeguard points in the code to avoid crashing and report any exception to the user so it has an opportunity to just click and copy/paste the exception to a github issue.

@madskristensen, Is this something that we could add? (to the most problematic places in the code, callbacks/commands that can crash...etc.)

**Comment by xoofx** [comment]
Incidentally, right after I created an issue, the issue #64 came with the problem I described here, and the person was able to get a log only by going to the Application log viewer, which is unlikely to happen often. So we need to make sure that the extension doesn't crash, and if there is a parsing bug, it doesn't crash VS but let the user aware of it and able to easily report the problem.

**Comment by madskristensen** [comment]
We can't really set up a global error handling mechanism. It has to be done on every edge of the code - as close to the user as possible. The only way to do that is to go through the code and apply try/catch blocks around possible problem areas. It's not a simple thing. 

I suggest we do it as we find issues and fix them

**Comment by xoofx** [comment]
Ok, will try to submit a first attempt on this.

**Comment by xoofx** [comment]
This should be partially fixed in the commit 9c32d84. If there is a parsing exception in markdig, It will produce an error in the Error pane and output window pane like this:

![markdown_editor_error_handling](https://cloud.githubusercontent.com/assets/715038/18778247/b8c9341c-8173-11e6-9757-6d86ce2b7047.png)

Also, the parser is still trying to parse the markdown document with a simpler/safer pipeline (almost no extensions enabled), to still allow the editor to work.

**Comment by xoofx** [comment]
Hi @madskristensen, do you think we can make a public release of the editor with the latest bits and fixes?

**Comment by madskristensen** [comment]
Sure, I'll do it later today
