### ISSUE TITLE
copying a string with a dot in it to a [] crashes Visual Studio.

### ISSUE THREAD

**Issue by ardimedia** [madskristensen/MarkdownEditor#65]
### Installed product versions
- Visual Studio: Visual Studio Enterprise 2015 (14.0.25431.01 Update 3)
- This extension: 1.9.173

### Description
I am in a markdown file. Copy a string like "something.com" inside a [], Visual Studio crashes,

### Steps to recreate
1. Open a markdown file with some text in it.
2. Ctrl-C a text which looks like that: something.com
3. Go to a section in the markdown, where there is [].
4. Move the cursor between []
5. Ctrl-V
6. Visual Studio will crash

### Current behavior
Visual Studio crashes.

### Expected behavior
Visual Studio should not crash.

**Comment by madskristensen** [comment]
I cannot reproduce this issue with the latest version of this extension. Can you try to specify the exact repro steps that makes VS crash?

**Comment by Enigma644** [comment]
I am also getting crashes a lot when editing links.
I have not yet pinned down what exactly causes the problem. I suspect it's something to do with when MarkdownEditor tries to resolve a link. It seems very intermittent.

**Comment by xoofx** [comment]
Unable to reproduce it as well in the debugger... but there my be a conflict with another extension (like ReSharper)

**Comment by kirchsth** [comment]
I could reproduce it with a simple sample and added also a error stack. Maybe it helps in reproducing of the error.
![errorafterenter](https://cloud.githubusercontent.com/assets/21959385/19522882/06bd5342-9619-11e6-8d23-710a33d5455d.png)
![errorstack](https://cloud.githubusercontent.com/assets/21959385/19522884/0a5d5042-9619-11e6-8245-2e99f9731a91.png)
![okbefore](https://cloud.githubusercontent.com/assets/21959385/19522893/10484c00-9619-11e6-8e60-bc9f87b7d117.png)

[ReadMe1.txt](https://github.com/madskristensen/MarkdownEditor/files/539294/ReadMe1.txt)

**Comment by madskristensen** [comment]
Thanks for the detailed repro steps. I could reproduce the issue and have a fix on its way to the Gallery in a few minutes

**Comment by kirchsth** [comment]
Thank you for the fast bugfix and the tool at all. It's working on my side now
