### ISSUE TITLE
No custom stylesheet option

### ISSUE THREAD

**Issue by djohnst10** [madskristensen/MarkdownEditor#66]
### Installed product versions
- Visual Studio: 2015 Professional Update 3 (14.0.25431.01)
- Markdown Editor: 1.9.173

### Description
The option to generate the md-styles.css file is missing.

### Steps to recreate
1. Open a markdown document. I've tried a document that was a solution items and a document that was a project item.
2. Right click the markdown editor (not the preview).
3. There is no option to add a stylesheet.

### Current behavior
There is no option on the right-click menu to add a stylesheet.
![image](https://cloud.githubusercontent.com/assets/2738319/19004840/c46b8984-8725-11e6-9de2-d5a208cc7af7.png)

### Expected behavior
There should be an option on the right-click men to add a stylesheet.
![image](https://cloud.githubusercontent.com/assets/2738319/19004893/ff963e78-8725-11e6-87d2-03e48409e129.png)

**Comment by madskristensen** [comment]
I can see from your screenshot that the HTML editor is the base of the markdown editor. That was true when Web Essentials contained the markdown support, but not in this new markdown editor extension. Can you please make sure that you are using the very latest version of both Web Essentials and the Markdown Editor extension and report back if the problem persists?

**Comment by djohnst10** [comment]
The Web Essentials version is 3.0.235, the current version.

**Comment by djohnst10** [comment]
Any updates on this? Should I uninstall and reinstall Web Essentials or Markdown Editor? Any other way I can help?

**Comment by madskristensen** [comment]
If you have GlyphFriend extension installed, try to disable it and let me know if that works. It maps .md files to the HTML editor instead of the Markdown Editor extension

**Comment by djohnst10** [comment]
I did have GlyphFriend installed. I disabled it and now the right click menu has all items it should have.

![image](https://cloud.githubusercontent.com/assets/2738319/19661346/5c808c72-9a01-11e6-9d39-1d36a31dee0c.png)

**Comment by madskristensen** [comment]
@rionmonster can you remove the content type definition in Glyphfriend for .md files, please?

**Comment by rionmonster** [comment]
@madskristensen Just removed the .md definition and uploaded the build to the gallery. Let me know if that works for you.

**Comment by madskristensen** [comment]
@rionmonster Awesome, thanks so much :)

**Comment by djohnst10** [comment]
I installed the latest version of Glyphfriend (1.5.2.1) and I still have the same issue. Disabling the Glyphfriend extension fixes the issue again.

CC @rionmonster

**Comment by rionmonster** [comment]
@madskristensen 

Any other suggestions or ideas of what might be causing this behavior? I'll be glad to make any changes as necessary if they are fighting with this extension, although I would have thought that ignoring the .md types would resolve it.

**Comment by madskristensen** [comment]
@rionmonster  Yes, nuke the entire _MarkdownContentTypeDefinition.cs_ file. The content type to use for the _TextViewCreationListener_ is still `"markdown"`.

**Comment by rionmonster** [comment]
Will that kill the Emoji completion for Markdown files? That's the only reason that we even have Markdown in it's own separate definitions file. So would just using "markdown" as follows be sufficient :

````
[Export(typeof(IVsTextViewCreationListener))]
[ContentType("markdown")]
[TextViewRole(PredefinedTextViewRoles.Document)]
internal class MarkdownTextViewListener : IVsTextViewCreationListener
````

**Comment by madskristensen** [comment]
@rionmonster Yes, if you don't have the Markdown Editor extension installed. You technically only need to delete line 10-13 for Glyphfriend not to associate markdown files with the HTML editor,

**Comment by rionmonster** [comment]
Do you have a preference between nuking the file entirely or just the aforementioned lines (10-13) : 

````
[Export(typeof(ContentTypeDefinition))]
[Name(MarkdownContentType)]
[BaseDefinition("htmlx")]
public ContentTypeDefinition IMarkdownContentType { get; set; }
````

Either way, I can make the changes as soon as you need.

**Comment by madskristensen** [comment]
As the owner of Markdown Editor I'd prefer the entire file be nuked, but as the owner of Glyphfriend it would be smartest to keep it :)

Just removing line 10-13 will fix this issue.

**Comment by rionmonster** [comment]
"Why can't all these extensions just get along?"

All done. Updated Glyphfriend to 1.5.2.2 and it should resolve everything.

Personally, I'm not crazy about the Emoji-Completion myself. It was a request a few folks asked for and honestly I felt like it was a bit out of place in the extension. I'd like to see if I can get some type of telemetry set up to see when folks are actually triggering / loading the Emojis, but I feel like that's quite an interesting problem in itself.

**Comment by djohnst10** [comment]
I installed version 1.5.2.2 of Glyphfriend and I now the issue is fixed.
