### ISSUE TITLE
Incorrect parsing of code block with markdown characters

### ISSUE THREAD

**Issue by jongpieter** [madskristensen/MarkdownEditor#67]
### Installed product versions
- Visual Studio: 2015 Community
- This extension: 1.6.125

### Description
When working with a code block, the code inside the block is parsed correctly for the preview. 
However the autoindent and related text editor formatting, are causing the markdown code to be 
parsed incorrectly. Leading to incorrect indentations and formatting.

### Steps to recreate
1. In a markdown file, create a codeblock with markdown characters in the codeblock 
```md
    ```
    Syntax: svcutil.exe [/t:code]  <metadataDocumentPath>* | <url>* | <epr>
    ```
```
2. The codeblock will confuse the formatting for the later part of the document.

### Current behavior
Code in the codeblock should be excluded from document formatting functions, but is causing the document to be parsed incorrectly after the codeblock.

### Expected behavior
The code in the codeblock should not influence code formatting outside of the codeblock

**Comment by xoofx** [comment]
Some bugs have been fixed related to auto indent on latest version 1.9.173+ Could you try it?

**Comment by jongpieter** [comment]
Tried with the latest version 1.9.173

Codeblock
![markdown_codeblock_1](https://cloud.githubusercontent.com/assets/1541759/19188946/8a71fc5c-8c95-11e6-99e1-8b3d1e363280.PNG)

After pressing enter at the end of the first line with <> expression
![markdown_codeblock_2](https://cloud.githubusercontent.com/assets/1541759/19188947/8a733216-8c95-11e6-9c87-0026891b5c19.PNG)

**Comment by xoofx** [comment]
I'm unable to reproduce it with latest version. Are you sure that you have closed all the VS instances and reopened VS after installing the 1.9.173?

**Comment by jongpieter** [comment]
The plugin `Glyphfiend` seemed to override the Markdown settings, causing the formatting issues.

Uninstalling the plugin solved the problem
