### ISSUE TITLE
Option to Generate HTML File does not add HTML file to Shared Projects

### ISSUE THREAD

**Issue by djohnst10** [madskristensen/MarkdownEditor#69]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.10.180
### Description

I am using a Shared Project as a way to create a content only project that contains markdown files edited with the extension. When the Generate HTML File option is selected the HTML file is added to the same folder as the MD file but the HTML file is not added to the project.
### Steps to recreate
1. Create a C# Shared Project.
2. Add a Markdown file to the project name file1.md.
3. Right click the file in Solution Explorer and select Generate HTML File.
4. The file1.html file is created in the folder but is not added to the project.
### Current behavior

The HTML file is created but is not added to the project. The right click menu also shows a check mark beside the Generate HTML File item but that appears to be because the file exists, not that it is a part of the project.
### Expected behavior

The HTML file should be added as a project item and be nested under the MD file. The check mark beside the Generate HTML File right-click menu items should be based on whether the file exists **and** whether it is a part of the project.

**Comment by djohnst10** [comment]
Since file nesting doesn't work in shared projects per madskristensen/FileNesting#62, the HTML file should appear in the project at least.

**Comment by madskristensen** [comment]
Unfortunately, Shared Projects doesn't contain the APIs needed for this. That's also why FileNesting doesn't work for it. There is nothing I can do to fix the behavior from an extension
