### ISSUE TITLE
Generated HTML is not a complete document

### ISSUE THREAD

**Issue by djohnst10** [madskristensen/MarkdownEditor#71]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.10.180

### Description
The HTML generated by the option 'Generate HTML File' in the right-click menu for MD files in Solution Explorer does not have the minimum necessary to be considered a complete HTML document.

### Steps to recreate
1. Add a Markdown file to a project.
2. Make the content: \# Markdown file
3. Right click the file and select 'Generate HTML File'. In projects types that support it, an HTML file with the same base name as the MD file should be added to the project as a nested file under the MD file.
4. Open the HTML file. The content is: \<h1 id="markdown-file">Markdown file\</h1>

### Current behavior
The generated HTML is not a complete HTML document.

### Expected behavior
There should be options to control the template of the HTML that would allow the surrounding HTML to be specified.

**Comment by madskristensen** [comment]
See here how to control it https://github.com/madskristensen/MarkdownEditor/blob/master/README.md#auto-generate-html-files

**Comment by djohnst10** [comment]
Looks good. Look forward to testing this in the next release.

**Comment by madskristensen** [comment]
You can try it in the CI build here http://vsixgallery.com/extension/9ca64947-e9ca-4543-bfb8-6cce9be19fd6/
