### ISSUE TITLE
Invalid indentation on the 2nd line of indented code blocks

### ISSUE THREAD

**Issue by xoofx** [madskristensen/MarkdownEditor#8]
It seems that when using indented code blocks, the first line is correctly handled, but subsequent lines have a small spaces inserted before. You can see it spotted as a red line on the screenshot:

original code:
```
    block
    line1
    line2
    line3
```

![invalidindent](https://cloud.githubusercontent.com/assets/715038/16214693/f0ac8dde-3795-11e6-9785-9b7cece9414b.png)

**Comment by madskristensen** [comment]
@xoofx is this issue related to your last PR. I can't repro

**Comment by xoofx** [comment]
that could be a side effect somewhere else (e.g where the `SmartIndentCommandTarget.Match()` is used)
The strange thing is that the small gap is not a character, that's a change of styling in VS...

**Comment by madskristensen** [comment]
Could it be ReSharper messing it up?

**Comment by madskristensen** [comment]
Is this still a bug we need to track here or can it be closed?

**Comment by xoofx** [comment]
Actually, this bug might come from Markdig that is starting the span for indented code blocks on the first line after the 4 indent characters. Then only after this the code blocks would use the font of the indented code blocks. It should starts at the beginning of the indent (before the 4 space chars)

**Comment by xoofx** [comment]
The commit above in markdig should fix the issue
