### ISSUE TITLE
*** a quick support for latex math ***

### ISSUE THREAD

**Issue by jiapw** [madskristensen/MarkdownEditor#80]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.1.21

### Description
please convert anything like $\frac{1}{2^n}\cdot\frac{512-k}{512}$ or 
$$$
$\frac{1}{2^n}\cdot\frac{512-k}{512}$
$$$
into 
a \<img\> referring https://latex.codecogs.com/gif.latex?\frac{1}{2^n}\cdot\frac{512-k}{512} when previewing and generating HTML. 
Now it is a \<span\> with class="math", which dosen't make any sense.

**Comment by madskristensen** [comment]
Duper of #77
