### ISSUE TITLE
How is mermaid supported?  A bug?

### ISSUE THREAD

**Issue by jiapw** [madskristensen/MarkdownEditor#81]
​```sequence
Alice->Bob: Hello Bob, how are you?
Note right of Bob: Bob thinks
Bob-->Alice: I am good thanks!
​```

is rendered just as plaintext. How is mermaid supported

**Comment by madskristensen** [comment]
inside code blocks like so:

\`\`\`mermaid 
sequence Alice->Bob: Hello Bob, how are you? Note right of Bob: Bob thinks Bob-->Alice: I am good thanks!
\`\`\`

**Comment by jiapw** [comment]
I did so. but ....  (right-hand side with white background is the preview
window)

[image: Inline image 1]
