### ISSUE TITLE
Provide a convenient way to create a new markdown document (from a link)

### ISSUE THREAD

**Issue by igorushi** [madskristensen/MarkdownEditor#83]
### Installed product versions
- Visual Studio: 2015, 2017
- This extension: 1.10.186

### Description
[[Feature request]] Provide a convenient way to create a new markdown document (from a link)

### Steps to recreate
![1](https://cloud.githubusercontent.com/assets/7131092/21240160/b4568f3e-c312-11e6-8e9a-51e70d2f3f97.png)

### Expected behavior
It could be great if there will be a quick 'bulb' fix `Create a file <file-name>`

**Comment by igorushi** [comment]
@madskristensen, @xoofx , it looks pretty straightforward, do you mind if I'll implement it myself?

**Comment by madskristensen** [comment]
That would be great. Go for it!! Did you think of adding a command to a light bulb to create the file?

**Comment by igorushi** [comment]
@madskristensen, yes, would like to check a link related ErrorTag presence and if there is any  - add a suggested action (bulb command).

**Comment by madskristensen** [comment]
@igorushi Makes sense. I love the idea
