### ISSUE TITLE
HTML highligting

### ISSUE THREAD

**Issue by xoofx** [madskristensen/MarkdownEditor#9]
Is it possible to activate default VS HTML highlighting/classifiers on HTML span/blocks that are identified by Markdig? (to have a better highlighting experience for this case)

**Comment by madskristensen** [comment]
It can be done by basing the editor on the HTMLX content type just like what Web Essentials did. However, there is a reason I didn't do that this time around and it has to do with how Artifacts (code blocks/inline) are handled. It will produce red squigglys around HTML tags in a lot of cases and also performance will take a hit. I think for now it's better not to do that, but we can at least classify HTML blocks better so they look more like the HTML editor

**Comment by xoofx** [comment]
No problem. Just wondering, how this nested syntax highlighting is working? (A link to some code I could look at it?) Could something be improved in Markdig?

**Comment by madskristensen** [comment]
Does this still repro with the latest bits? The language service should remove all references to HTML editor
