### ISSUE TITLE
Preview Incorrectly Renders Tables

### ISSUE THREAD

**Issue by Good-man** [madskristensen/MarkdownEditor#90]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.1.21]

### Description
The preview doesn't render tables correctly.

### Steps to recreate
Copy/paste the table below into the Markdown Editor extension. 

~~~~~
|Branch     |Purpose/Description|
|---        |---                |
|`master`|This is the main branch.  The branch contains code that has been released to production. This is a permanent branch.|
|`hotfix/<bug number>`|Hotfix branches are used for [fixing code](change%20management.md) that has already been released to production.  Hotfix branches are created from **master**. |
|`release/<version number>`|Release branches are used for testing [enhancements](change%20management.md) prior to release.  Release branches are created from **develop**.|
|`develop`|The develop branch is used for merging features together, prior to release.  This is a permanent branch. |
|`feature/<feature name>`|Feature branches are used for developing new features and [enhancements](change%20management.md).  They are also used for fixing code that has not been released. Feature branches are created from **develop**.|
~~~~~

### Current behavior
1. Notice how the extension's preview renders the last cell (bottom right) in the third column. 
2. Now remove **bold** from the word develop in the last cell.
3. Notice how the extension renders the last cell in the second column now.

### Expected behavior
This is how it is supposed to be rendered:  

|Branch     |Purpose/Description|
|---        |---                |
|`master`|This is the main branch.  The branch contains code that has been released to production. This is a permanent branch.|
|`hotfix/<bug number>`|Hotfix branches are used for [fixing code](change%20management.md) that has already been released to production.  Hotfix branches are created from **master**. |
|`release/<version number>`|Release branches are used for testing [enhancements](change%20management.md) prior to release.  Release branches are created from **develop**.|
|`develop`|The develop branch is used for merging features together, prior to release.  This is a permanent branch. |
|`feature/<feature name>`|Feature branches are used for developing new features and [enhancements](change%20management.md).  They are also used for fixing code that has not been released. Feature branches are created from **develop**.|

**Comment by tobiasbunyan** [comment]
Having similar problems with tables when adding a table referencing source control paths.  For example, this renders ok
```
Status|Path
------|----
Active|$/val
Active|$val
```
but add in / to the second path value
```
Status|Path
------|----
Active|$/val
Active|$/val
```
and the output goes wonky

Escaping the second $ / (i.e. \$) fixes the problem.  I'm not aware of $ being a special char in markdown?

**Comment by xoofx** [comment]
These are issues with markdig (the markdown processor), can you please add issues there https://github.com/lunet-io/markdig/issues

**Comment by xoofx** [comment]
Also  @tobiasbunyan can you create a different issues (they are not the same)

**Comment by madskristensen** [comment]
I'll close this bug since it's tracked on the Markdig repo
