### ISSUE TITLE
Mermaid preview not showing graph nodes labels

### ISSUE THREAD

**Issue by raviolua** [madskristensen/MarkdownEditor#92]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.10.186

### Description
Mermaid preview not showing graph nodes labels

### Steps to recreate
1. Create file *.md
2. Fill with content:

> &#96;&#96;&#96;mermaid
> graph TD;
>     A--sth-->B{bb};
> &#96;&#96;&#96;

### Current behavior
Nodes are visible in preview window without inner labels ("A" or "bb"). Also no "std" label on arrow.

### Expected behavior
Same as standard mermaid that is nodes with "A" and "bb" labels inside them and "sth" label on arrow.

**Comment by vassilyl** [comment]
A workaround is to disable html labels: `flowchart: {htmlLabels: false}`, see knsv/mermaid#142

**Comment by yudigoh** [comment]
add md-template.html to the directory where you have your md files.

put the following content into your template:

```html
<!DOCTYPE html>
<html>
<head>
    <title>[title]</title>
</head>
<body>

    [content]
    <script>
        var config = {
            startOnLoad:true,
            flowchart:{
                htmlLabels:false
            }
        };
        mermaid.initialize(config);
    </script>
</body>
</html>
````
