### ISSUE TITLE
Add feature to continue lists & quote blocks

### ISSUE THREAD

**Issue by jeffchasin** [madskristensen/MarkdownEditor#97]
## Feature Request

* Continue list item or quote block
    - When pressing Enter at the end of a list item or in a quote block: an asterisk, number or greater than symbol with a space is auto-generated to continue the list or block
    - Enter on a blank list item won't be continued
    - Pressing Tab on the blank list item will indent it

Would love to see this added to MarkdownEditor if possible.

**Comment by madskristensen** [comment]
This has been in for a long time. Do you have any other extension installed that might take over the ENTER key event? Resharper?

**Comment by jeffchasin** [comment]
Feeling totally dumb for not checking first, fixed!
