### ISSUE TITLE
GitHub Table not Rendering

### ISSUE THREAD

**Issue by CheetahChrome** [madskristensen/MarkdownEditor#99]
I have a table markdown which renders properly in GitHub's page but not in Visual Studio 2015 extension version 1.10.196. See [babelmark  failure example](https://babelmark.github.io/?text=%0A%23%23Turnkey+Example%3A+%0A%0A%60%60%60C%23%0A%23using+CoolCommandLine%3B%0A++++%0Astatic+void+Main(string%5B%5D+args)%0A%7B%0A++%2F%2F+Look+for+the+%22-L%22+on+the+command+line+and+if+found+simulate+an+action+by+writing+the+event+out+to+the+console.+%0A++(new+CommandLineManager()).AddOption(%22L%2C+List%22%2C+%22List+the+data.%22%2C+(clm)%3D%3E+Console.WriteLine(%24%22Listing+operation+returned+%7Bclm.L%7D+%22))%0A++++++++++++++++++++++++++++.Execute(args)%3B%0A%7D%0A%60%60%60+%0A+Code+%7C+What+it+Does%0A+----+%7C+------------%0A%60using+CoolCommandLine%3B%60+%7C+After+installation+and+reference+to+the+project+is+done%2C+one+adds+a+%60%23using+CoolCommandLine%3B%60+to+the+file.). (Full example found [here](https://github.com/CheetahChrome/CoolCommandLine/blob/master/README.md)).

Here is example script:

```
##Turnkey Example: 

` ` `C#
#using CoolCommandLine;
    
static void Main(string[] args)
{
  // Look for the "-L" on the command line and if found simulate an action by writing the event out to the console. 
  (new CommandLineManager()).AddOption("L, List", "List the data.", (clm)=> Console.WriteLine($"Listing operation returned {clm.L} "))
                            .Execute(args);
}
` ` `
Code | What it Does
 ---- | ------------
 `using CoolCommandLine;` | After installation and reference to the project is done, one adds a `#using CoolCommandLine;` to the file.
```

*** Note that I have spaced out the three tics ( ` ) in the above example; one will need to unspace both sets of them to get the same situation.**

**This is what it should show:**

##Turnkey Example: 

```C#
#using CoolCommandLine;
    
static void Main(string[] args)
{
  // Look for the "-L" on the command line and if found simulate an action by writing the event out to the console. 
  (new CommandLineManager()).AddOption("L, List", "List the data.", (clm)=> Console.WriteLine($"Listing operation returned {clm.L} "))
                            .Execute(args);
}
```

 Code | What it Does
 ---- | ------------
 `using CoolCommandLine;` | After installation and reference to the project is done, one adds a `#using CoolCommandLine;` to the file.

**This is how it renders in Visual Studio**

![markdown](https://cloud.githubusercontent.com/assets/1110966/23315786/f2d4af3a-fa84-11e6-848a-26842edcf849.png)

Am I missing something... or is there a switch to specify for `GitHub` rendering?

**Comment by xoofx** [comment]
According to [babelmark](https://babelmark.github.io/?text=Code+%7C+What+it+Does%0A+----+%7C+------------%0A+%60using+CoolCommandLine%3B%60+%7C+After+installation+and+reference+to+the+project+is+done%2C+one+adds+a+%60%23using+CoolCommandLine%3B%60+to+the+file.) markdig (advanced - the same config that is used by MarkdownEditor) should handle it correctly 

Just tested also with [latest MarkdownEditor](http://vsixgallery.com/extension/9ca64947-e9ca-4543-bfb8-6cce9be19fd6/) and I'm getting the correct table. Which version are you actually using?

**Comment by CheetahChrome** [comment]
> Which version are you actually using?

Version 1.10.186 Visual Studio 2015 latest SP. I see the link you sent is X.196. I installed via `Extensions and Updates` on Friday and that is the version it gave; strange. I uninstalled and installed v X.196 and the same happened...but see next section.

> According to babelmark...

Thanks for showing me babelmark.  I found the problem by **adding more of the markup** from my page.  What was discovered was the proceeding code block *above the table* causes the failure.  When that is added, bablemark for `markdig` fails. See failure:

[bablemark failure](https://babelmark.github.io/?text=%0A%23%23Turnkey+Example%3A+%0A%0A%60%60%60C%23%0A%23using+CoolCommandLine%3B%0A++++%0Astatic+void+Main(string%5B%5D+args)%0A%7B%0A++%2F%2F+Look+for+the+%22-L%22+on+the+command+line+and+if+found+simulate+an+action+by+writing+the+event+out+to+the+console.+%0A++(new+CommandLineManager()).AddOption(%22L%2C+List%22%2C+%22List+the+data.%22%2C+(clm)%3D%3E+Console.WriteLine(%24%22Listing+operation+returned+%7Bclm.L%7D+%22))%0A++++++++++++++++++++++++++++.Execute(args)%3B%0A%7D%0A%60%60%60+%0A+Code+%7C+What+it+Does%0A+----+%7C+------------%0A%60using+CoolCommandLine%3B%60+%7C+After+installation+and+reference+to+the+project+is+done%2C+one+adds+a+%60%23using+CoolCommandLine%3B%60+to+the+file.)

**Comment by xoofx** [comment]
I don't see any failure with the example above on both MarkdownEditor (which is using markdig advanced) and Markdig (advanced)

**Comment by CheetahChrome** [comment]
I understand what you are saying concur. But the issue, at this point, lies within the *usage of the library* in Visual Studio solely. This is what is what is shown using version 196 on the MD file in Visual Studio 2015:


![2017-02-28_7-06-58](https://cloud.githubusercontent.com/assets/1110966/23408365/055562be-fd85-11e6-9e40-3934e6264738.png)

**Comment by xoofx** [comment]
yes, but strangely I'm unable to reproduce this in VS 2015 with the MarkdownEditor... for the exact text you copied above. But It might not work for the text you are really using (most likely a bug in markdig pipe tables)

**Comment by madskristensen** [comment]
I can reproduce the issue if I copy/paste directly. However, the example had an issue where there are spaces in between the backticks surrounding the C# code block. Removing those spaces fixed the issue and it renders correctly

**Comment by CheetahChrome** [comment]
> there are spaces in between the back-ticks surrounding the C# code block.

I had to do that *for the example* because this issue page takes three ticks literally and creates, or closes a code block. There is no way to escape three ticks in an existing code block AFAIK. (```\`\`\`C#```)

> Removing those spaces fixed the issue 

In the original document I removed any and all superfluous spaces and this is what I see. Note the highlight showing no spaces just a line feed.

![2017-02-28_14-38-15](https://cloud.githubusercontent.com/assets/1110966/23435470/d242afcc-fdc4-11e6-9763-dd3ad99ab9f4.jpg)

**Comment by xoofx** [comment]
> There is no way to escape three ticks in an existing code block AFAIK. (\`\`\`C#)

you can use a higher number of sticks (>3) to enclose a lower code block. The number of sticks have to match between the open/close.

Could you post the full table instead of a cut of it, as it is often the content of the table that can break its detection.

**Comment by CheetahChrome** [comment]
@BOT-Man-JL Now I am _tic_-ed off! lol

Upon fixing the missing tic which you identified, the table renders appropriately! Thanks for everyone who looked into this!

![2017-03-01_8-12-50](https://cloud.githubusercontent.com/assets/1110966/23466036/2b908e72-fe57-11e6-8283-ff0bee59f5ab.png)

**Comment by xoofx** [comment]
Good catch  @BOT-Man-JL  !

@CheetahChrome a small note that for headings (`# ...`) you need to have a whitespace after a `#` (as per CommonMark specs)

**Comment by CheetahChrome** [comment]
> you need to have a whitespace after a...

@xoofx Ugg! I learned [TeX](https://en.wikipedia.org/wiki/TeX) back in the 80's, Word/VSTO in the 21st century and now Markdown. :-)

It appears I have a lot to learn still. Thank you for your time (the most important thing of all) and helping me learn. If there is anything I can do going forward to repay, don't hesitate to let me know.
